version: '3.8'

services:
    database:
        image: 'postgres:latest'
        restart: always
        env_file:
            - ./.env
        ports:
          - '5432:5432'
        volumes:
          - postgres-data:/var/lib/postgresql/data
    app:
        build: .
        env_file: 
            - ./.env
        command: ./main
        ports:
            - "8000:8000"
        depends_on: 
            - database

volumes:
    postgres-data: